Functional improvements
+ Use latest nix.
+ Support for package-manager-installed nix, as well as installing via nixpkgs.
+ Add commands for managing the systemd service/socket.

diff --git a/archlinux-nix b/archlinux-nix
--- a/archlinux-nix
+++ b/archlinux-nix
@@ -1,16 +1,18 @@
 #!/bin/sh
 
-sandbox_binaries="bash bzip2 env gzip mkdir mv perl tar tr xz"
-default_nixos_version="17.09"
+sandbox_binaries="bash bzip2 env gzip mkdir mv tar tr xz"
+default_nixos_version="19.03"
 default_group="nixbld"
 conf_file=/etc/nix/nix.conf
 
 dest=/nix
 
+nix_version=2.2.2
+
 case $(uname -m) in
-  x86_64) system=x86_64-linux; hash=6312837aee33306cdbb351b75ba1638b89d21b30f0caf0346f9a742425f197ee ;;
-  i?86) system=i686-linux; hash=5333384cf1b2f0d9b66d3c4db2643649f0c20d1ed5a0f0dac47ad0092a5874a3 ;;
-  aarch64) system=aarch64-linux; hash=ffe6c5c014c47ca8476c696a55bbd96beffb71f32c5d1a5da66d338a2aebbf17 ;;
+  x86_64) system=x86_64-linux; hash=7ce46548509837d4bc8d01b63973f8fb8972fbbe8ba6a9b5e929cf5954c3d85e;;
+  i?86) system=i686-linux; hash=b055b9ac5e65d43cb6b1d1fe99eb106371a6b5782c3522209a73f473dc7b8779;;
+  aarch64) system=aarch64-linux; hash=1d5c5ede3d7be3963f34f6b51a7b37b3ce3adc5ce623f2a50c11501b9c95bd4e;;
   *) system=""; hash="" ;;
 esac
 
@@ -19,7 +21,20 @@ oops() {
   exit 1
 }
 
-install() {
+pm_installed() {
+  which nix 2>/dev/null | grep -q '^/usr'
+}
+
+nix_installed() {
+  local nix=$(which nix 2>/dev/null)
+  [ ! -z $nix ] && echo `realpath $nix` | grep -q '^/nix'
+}
+
+do_install() {
+  if pm_installed; then
+    oops "Nix was installed via some other package manager (e.g. AUR). You should use that if you need to update it."
+  fi
+
   if [ -z "$system" ]; then
     oops "No binary is available for this system"
   fi
@@ -32,10 +47,10 @@ install() {
   }
   trap cleanup EXIT INT QUIT TERM
 
-  tarball="$tmpDir/$(basename "$tmpDir/nix-2.0-$system.tar.bz2")"
-  url="https://nixos.org/releases/nix/nix-2.0/nix-2.0-$system.tar.bz2"
+  tarball="$tmpDir/$(basename "$tmpDir/nix-$nix_version-$system.tar.bz2")"
+  url="https://nixos.org/releases/nix/nix-$nix_version/nix-$nix_version-$system.tar.bz2"
 
-  echo "downloading Nix 2.0 binary tarball for $system from '$url' to '$tmpDir'..."
+  echo "downloading Nix $nix_version binary tarball for $system from '$url' to '$tmpDir'..."
   curl -L "$url" -o "$tarball" || oops "failed to download '$url'"
 
   hash2="$(sha256sum -b "$tarball" | cut -c1-64)"
@@ -47,14 +62,14 @@ install() {
   unpack=$tmpDir/unpack
   mkdir -p "$unpack"
   < "$tarball" bzcat | tar x -C "$unpack" || oops "failed to unpack '$url'"
-  self="$unpack/nix-2.0-$system"
+  self="$unpack/nix-$nix_version-$system"
 
   mkdir -pm 0755 "$dest/store" && chown root.root "$dest" "$dest/store"
   cp -a -t "$dest/store/" "$self/store/"* || oops "failed to copy store"
 
-  nix="$dest/store/$(cd "$self/store" && ls -d *-nix-*)"
+  local nix="$dest/store/$(cd "$self/store" && ls -d *-nix-$nix_version)"
 
-  echo "initialising Nix database..." >&2
+  echo "Initialising Nix database..." >&2
   if ! "$nix/bin/nix-store" --init; then
     oops "failed to initialize the Nix database"
   fi
@@ -69,15 +84,15 @@ install() {
     oops "unable to install Nix into your default profile"
   fi
 
-  ln -s /nix/var/nix/profiles/default/etc/profile.d/nix*.sh /etc/profile.d/
+  ln -s $dest/var/nix/profiles/default/etc/profile.d/nix*.sh /etc/profile.d/
 }
 
 install_sandbox() {
   version=$1
-  mkdir -p /nix/var/nix/profiles/arch-system || exit 1
+  mkdir -p $dest/var/nix/profiles/arch-system || exit 1
   NIX_REMOTE="" nix-build \
     --option build-use-sandbox false \
-    -o /nix/var/nix/profiles/arch-system/build-sandbox \
+    -o $dest/var/nix/profiles/arch-system/build-sandbox \
     -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/$version.tar.gz \
     -E 'with import <nixpkgs> {}; buildEnv { name = "arch-system-build-sandbox"; paths = [ bash bzip2 coreutils gnutar gzip perl xz ]; }' || exit 1
 }
@@ -205,8 +220,8 @@ build_users_group() {
   [ -f "$conf_file" ] && grep '^\s*build-users-group\s*=' "$conf_file" | sed 's/^.*=\s*\(\w*\)\W/\1/'
 }
 
-using_sandbox() {
-  [ -f "$conf_file" ] && grep -q '^\s*build-use-sandbox\s*=\s*true' "$conf_file"
+sandbox_disabled() {
+  [ -f "$conf_file" ] && grep -q '^\s*build-use-sandbox\s*=\s*false' "$conf_file"
 }
 
 delete_use_sandbox() {
@@ -215,20 +230,83 @@ delete_use_sandbox() {
   fi
 }
 
-append_use_sandbox() {
+append_disable_sandbox() {
   delete_use_sandbox
-  echo 'build-use-sandbox = true' >> "$conf_file"
+  echo 'build-use-sandbox = false' >> "$conf_file"
+}
+
+check_loaded() {
+  systemctl show $1 --property=LoadState | grep -q "=loaded"
+}
+
+daemon_service_loaded() {
+  check_loaded nix-daemon.service
+}
+
+daemon_socket_loaded() {
+  check_loaded nix-daemon.socket
+}
+
+daemon_loaded() {
+  daemon_service_loaded && daemon_socket_loaded
+}
+
+daemon_socket_active() {
+  systemctl --quiet is-active nix-daemon.socket
+}
+
+stop_daemon_service() {
+  if daemon_service_loaded; then
+    systemctl stop nix-daemon.service
+  fi
+}
+
+stop_daemon_socket() {
+  if daemon_service_loaded && daemon_socket_active; then
+    systemctl disable --now nix-daemon.socket
+  fi
+}
+
+start_daemon_socket() {
+  if daemon_socket_loaded; then
+    systemctl enable nix-daemon.socket
+    systemctl start nix-daemon.socket
+  fi
+}
+
+link_system_unit_from_profile() {
+  systemctl link $dest/var/nix/profiles/$1/lib/systemd/system/$2
+}
+
+load_daemon() {
+  if nix_installed; then
+    link_system_unit_from_profile default nix-daemon.service
+    link_system_unit_from_profile default nix-daemon.socket
+  else
+    systemctl revert nix-daemon.socket
+    systemctl revert nix-daemon.service
+  fi
+
+  systemctl daemon-reload
 }
 
 do_status() {
-  sandbox=no
-  using_sandbox && sandbox=yes
-  group=$(build_users_group)
+  if pm_installed; then
+    echo "Nix installed via package manager ($(which nix))"
+  elif nix_installed; then
+    echo "Nix self-installed"
+  else
+    oops "Nix not installed"
+  fi
+
+  local sandbox=yes
+  sandbox_disabled && sandbox=no
+  local group=$(build_users_group)
 
   if [ -n "$group" ]; then
     echo "Configured build group: $group"
 
-    exists=no
+    local exists=no
     group_exists $group && exists=yes
     echo "Group exists: $exists"
 
@@ -248,24 +326,48 @@ do_status() {
   echo "Using sandbox (recommended): $sandbox"
 
   if [ $sandbox = yes ]; then
-    exists=no
-    sandbox_exists && exists=yes
-    echo "Sandbox exists: $exists"
+    if pm_installed; then
+      exists=no
+      sandbox_exists && exists=yes
+      echo "Sandbox installed: $exists"
+    fi
 
-    paths=$(sandbox_paths)
+    local paths=$(sandbox_paths)
 
     if [ -n "$paths" ]; then
       echo "Sandbox paths:"
       for path in $paths; do
         echo " - $path"
       done
-    else
+    elif pm_installed; then
       echo "Sandbox paths missing from config file"
+    else
+      echo "Sandbox paths not required"
     fi
+  fi
+
+  echo -n "Nix-daemon service: "
+  if daemon_service_loaded; then
+    echo loaded
+  else
+    echo not loaded
+  fi
+
+  echo -n "Nix-daemon socket: "
+  if ! daemon_socket_loaded; then
+    echo not loaded
+  elif daemon_socket_active; then
+    echo active
+  else
+    echo not active
   fi
 }
 
-do_set_sandbox() {
+do_install_sandbox() {
+  if nix_installed; then
+    oops "Sandbox paths not required"
+  fi
+
   version=$1
 
   if [ -z "$version" ]; then
@@ -279,10 +381,10 @@ do_set_sandbox() {
   append_sandbox_paths || exit 1
 
   echo "Enabling sandboxing ..."
-  append_use_sandbox || exit 1
+  delete_use_sandbox || exit 1
 
   echo "Killing daemon ..."
-  systemctl stop nix-daemon
+  stop_daemon_service
 }
 
 do_delete_sandbox() {
@@ -291,7 +393,7 @@ do_delete_sandbox() {
   delete_use_sandbox || exit 1
 
   echo "Killing daemon ..."
-  systemctl stop nix-daemon
+  stop_daemon_service
 
   echo "Unlinking sandbox ..."
   delete_sandbox || exit 1
@@ -299,7 +401,15 @@ do_delete_sandbox() {
   echo "You may wish to run 'nix-store --gc' to delete files"
 }
 
-do_set_build_group() {
+do_disable_sandbox() {
+  echo "Disabling build sandboxing ..."
+  append_disable_sandbox || exit 1
+
+  echo "Killing daemon ..."
+  stop_daemon_service
+}
+
+do_setup_build_group() {
   group=$1
 
   if [ -z "$group" ]; then
@@ -313,7 +423,7 @@ do_set_build_group() {
   append_build_group $group
 
   echo "Killing daemon ..."
-  systemctl stop nix-daemon
+  stop_daemon_service
 
   echo "Setting permissions on nix store ..."
   create_store $group
@@ -336,7 +446,7 @@ do_delete_build_group() {
     delete_build_group
 
     echo "Killing daemon ..."
-    systemctl stop nix-daemon
+    stop_daemon_service
 
     echo "Resetting permissions on nix store ..."
     restore_store
@@ -346,29 +456,64 @@ do_delete_build_group() {
   delete_users $group
 }
 
-do_install() {
-  install
+do_enable_nix_daemon() {
+  if ! daemon_loaded; then
+    echo "Loading nix-daemon into systemd ..."
+    load_daemon || exit 1
+
+    if ! daemon_loaded; then
+      echo "nix-daemon has not loaded. Exiting ..."
+      exit 1
+    fi
+  fi
+
+  if ! daemon_socket_active; then
+    echo "Activating nix-daemon.socket ..."
+    start_daemon_socket || exit 1
+  fi
+}
+
+do_disable_nix_daemon() {
+  if daemon_loaded; then
+    echo "Stopping and deactivating nix-daemon socket ..."
+    stop_daemon_socket || exit 1
+    echo "Stopping nix-daemon service (if running) ..."
+    stop_daemon_service || exit 1
+  else
+    echo "Nix-daemon is not loaded"
+  fi
 }
 
 usage() {
   echo "$(basename $0) <COMMAND>"
   echo -e "\nCOMMAND:"
 
-  echo -e "\tinstall\n\t\tInstall Nix"
+  if [ ! pm_installed ]; then
+    echo -e "\tinstall\n\t\tInstall Nix"
+  fi
 
   echo -e "\tstatus\n\t\tList current status"
 
-  echo -e "\tset-sandbox [VERSION]"
+  echo -e "\tinstall-sandbox [VERSION]"
   echo -e "\t\tSetup sandbox using binaries from specified NixOS version (defaults to $default_nixos_version)"
 
   echo -e "\tdelete-sandbox"
   echo -e "\t\tDelete sandbox and remove sandbox config"
 
-  echo -e "\tset-build-group [GROUP]"
+  echo -e "\tdisable-sandbox"
+  echo -e "\t\tDisable sandboxing"
+
+  echo -e "\tsetup-build-group [GROUP]"
   echo -e "\t\tCreate a group of build users and add to config (defaults to $default_group)"
 
   echo -e "\tdelete-build-group [GROUP]"
   echo -e "\t\tDelete group and users (defaults to existing group given in nix.conf)"
+
+  echo -e "\tenable-nix-daemon"
+  echo -e "\t\tEnable and start the nix-daemon"
+
+  echo -e "\tdisable-nix-daemon"
+  echo -e "\t\tDisable and stop the nix-daemon"
 }
 
 command=$1
@@ -377,10 +522,13 @@ shift
 case $command in
   'install') do_install ;;
   'status') do_status ;;
-  'set-sandbox') do_set_sandbox "$@" ;;
+  'install-sandbox') do_install_sandbox "$@" ;;
   'delete-sandbox') do_delete_sandbox "$@" ;;
-  'set-build-group') do_set_build_group "$@" ;;
+  'disable-sandbox') do_disable_sandbox ;;
+  'setup-build-group') do_setup_build_group "$@" ;;
   'delete-build-group') do_delete_build_group "$@" ;;
+  'enable-nix-daemon') do_enable_nix_daemon ;;
+  'disable-nix-daemon') do_disable_nix_daemon ;;
   'help' | '--help' | '-h' | '') usage ;;
   *)  oops "$(basename $0): unknown option '$command $@'" ;;
 esac
